version: '3.3'
services:
  collect-binancefutures:
    environment:
      - EXCHANGE=binance
      - OUTPUT_PATH=raw_data
      - SYMBOLS=btcusdt,btctusd
    volumes:
      - '/home/ec2-user/exchange_data/raw_data:/raw_data'
    restart: always
    image: 'collect-binancefutures:mia'
# docker run -e EXCHANGE='binancefutures' -e OUTPUT_PATH='testdocker' -e SYMBOLS='btcusdt,ethusdt' -v /home/ec2-user/collect-binancefutures/testdocker:/testdocker --restart-always ^Cllect-binancefutures:
# mia
